### PR TITLE
Fix examples/interactive_browser/config.ru so it works in the browser

### PR DESCRIPTION
**Pull request by jf**
was just looking through the examples, and trying to get this one to run. Had to make these changes to get them to work in the browser.

## Types of Changes

- Bug fix

## Contribution

- [ ] I added tests for my changes.
- [x] I tested my changes locally.
- [x] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Review by ioquatix — APPROVED** [review]

**Comment by ioquatix** [comment]
Thanks for this, I have not worked on this code base for a looong time, so it probably needs some TLC.

**Comment by jf** [comment]
sure. I hope this codebase gets some love! I may just use it...

**Comment by jf** [comment]
if you could help me understand the change, and why this fix was necessary: what happened? I seem to recall (but can't locate the source now, unfortunately), you saying somewhere that the data is JSON-encoded by default... but I'm not sure about the change that necessitated going from `${pineapple_count}` to `${pineapple_count.buffer}`. So previously calling `to_s` on the message would do ".buffer.to_s"?

**Comment by ioquatix** [comment]
The [general message classes were introduced here](https://github.com/socketry/protocol-websocket/commit/e235879b98a99d424adbda0bd5e3f918f0914cbb).

The [`JSONMessage` message class was introduced here](https://github.com/socketry/protocol-websocket/commit/ae596b7e77a74ce18847d0a71f8b4c623411d912).

Before that, the handling of messages was more ambiguous and harder to extend as you can see in the first PR.

**Pull request merged**
